### ISSUE TITLE
pvc issue

### ISSUE THREAD

**Issue by da00891219** [sharkymark/v2-templates#10]
pvc is not bounded and in pending and workspace creation fails
Error: client rate limiter Wait returned an error: context deadline exceeded
persistentvolume-controller  waiting for first consumer to be created before binding
pvc status - Pending

I am using OKE cluster on OCI and how to enable Dynamic Persistent Volume Claim?

**Comment by sharkymark** [comment]
@da00891219 On some clouds, `wait_until_bound` is needed

```hcl
resource "kubernetes_persistent_volume_claim" "home-directory" {
  metadata {
    name      = "home-coder-${data.coder_workspace.me.owner}-${data.coder_workspace.me.name}"
    namespace = var.workspaces_namespace
  }
  wait_until_bound = false  
```
