### ISSUE TITLE
502 bad gateway error for pod-with-eclipse template

### ISSUE THREAD

**Issue by da00891219** [sharkymark/v2-templates#5]
We are using eclipse template - https://github.com/sharkymark/v2-templates/tree/main/pod-with-eclipse
Our coder oss runs on oracle oci infra on kubernetes (we installed using helm charts) - v0.13.1 (v2)

Issue#
workspace hits "502 bad gateway error". please refer screenshots attached.

![image](https://user-images.githubusercontent.com/112606830/215937514-80970e08-1e46-4786-8dca-b6e124d88f9c.png)

![image](https://user-images.githubusercontent.com/112606830/215937397-dcac84ef-95e9-4045-8d6b-ec224c3cd803.png)

**Comment by da00891219** [comment]
healthcheck fails

resource "coder_app" "code-server" {
  agent_id = coder_agent.coder.id
  slug          = "code-server"  
  display_name  = "VS Code"  
  icon     = "/icon/code.svg"
  url      = "http://localhost:13337"
  subdomain = false
  share     = "owner"

  healthcheck {
    url       = "http://localhost:13337/healthz"
    interval  = 3
    threshold = 10
  }
}

resource "coder_app" "eclipse" {
  agent_id      = coder_agent.coder.id
  slug          = "eclipse"  
  display_name  = "Eclipse"  
  icon          = "https://upload.wikimedia.org/wikipedia/commons/c/cf/Eclipse-SVG.svg"
  url           = "http://localhost:6081"
  subdomain = false
  share     = "owner"

  healthcheck {
    url       = "http://localhost:6081/healthz"
    interval  = 6
    threshold = 20
  } 
}

![image](https://user-images.githubusercontent.com/112606830/215939749-ba437d91-6792-4c52-958c-79f179bcf13c.png)

**Comment by sharkymark** [comment]
strange, works for me.

do any templates work, like just a basic code-server one?

<img width="1547" alt="image" src="https://user-images.githubusercontent.com/2022166/216046849-5860fd1e-d934-4df2-b8b6-83f64a091d64.png">

**Comment by da00891219** [comment]
how to launch eclipse IDE from there?

**Comment by da00891219** [comment]
we got it /opt/eclipse/eclipse is where eclipse ide is getting opened.

**Comment by da00891219** [comment]
The issue is control characters in template. I am using vscode for development of templates on windows machine. when I clone the git repo, its cloning with windows format and when I commit it should commit in unix format, which is not happening, hence I hit with this issue. Now I reinstalled git on my windows laptop and configured git to use "clone as is and commit in unix style" and which resolved the issue.

![git-checkout-options](https://user-images.githubusercontent.com/112606830/217139737-72be4817-7731-470f-af1a-1c1d24be3cab.PNG)
