### ISSUE TITLE
/bin/bash: line 17: ./remote-dev-server.sh: No such file or directory

### ISSUE THREAD

**Issue by da00891219** [sharkymark/v2-templates#6]
I am working on Jetbrains Gateway template to launch intellij ide using jetbrains gateway. I am following below template.
https://github.com/sharkymark/v2-templates/tree/main/pod-gateway-ide

I am hitting below error in coder startup -

https://github.com/sharkymark/v2-templates/tree/main/pod-gateway-ide

I am hitting below error in coder agent (while launching intellij ide)

2023-02-02 15:05:08.734 [DEBUG] (tailnet)       <./tailnet/conn.go:633> (*Conn).forwardTCPToLocal       dial local port {"port": 63342, "error": "dial tcp 127.0.0.1:63342: connect: connection refused"}

able to launch code-server, but error for intellij ide

**Comment by da00891219** [comment]
upgraded to v0.17.1 and issue is resolved.

**Comment by sharkymark** [comment]
@da00891219 the folder not being found would be if you used a container image with a community edition JetBrains IDE, since Gateway only works with paid JetBrains IDEs so the the remote file will not be there
