### ISSUE TITLE
jetbrains gateway ide

### ISSUE THREAD

**Issue by da00891219** [sharkymark/v2-templates#9]
I created pod-gateway-ide template and workspace.
I configured Jetbrains Gateway on my local and connected to the workspace.
I am able to open intellij ide.

https://github.com/sharkymark/v2-templates/tree/main/pod-gateway-ide

is this the behavior? or do we need to configure coder_app and launch IDE? if so, how to do that?

**Comment by sharkymark** [comment]
If you pull that repo, I have deprecated all Gateway projector templates because JetBrains has stopped Projector support. Use Gateway as they recommend. https://coder.com/docs/v2/latest/ides/gateway
